export const initValvestate = {
  VALVE: true,
  twoway: null,
  twoway1: null,
  Handle: null,
  IP_ENCLOSURE: 'Yes',
  PT_TRANSMIT: 'Yes',
  SOLENOID_MATERIAL: 'General',
  IP_TYPE: '+HART',
  TAG_NO: '', //API
  select: '',
  qset: 1, //카운터
  // angle: false,
  // segmentalBall: true,
  ValveType: null,
  END_CONNECTION: null,
  ACTUATOR_TYPE: null,
  MEDIUM_1: 'Liquid',
  proof: '내압',
  SOLENOID_CONNECT_TYPE: 'P.P',
  Explosion: 'Yes',
  AIR_SET_CONNECT_TYPE: 'PT',
  AirSupply1: true,
  IP_CONDUIT_AIR_CONNECT: 'PT',
  Electrical1: true,
  SOLENOID_MFG: false,
  LIMIT_MFG: false,
  IP_POSITIONER: 'Positioner',
  'P.P': false,
  'E.P': false,
  Smart: false,
  BODY_SIZE: '6 (1/4")',
  BODY: 'A216-WCB',
  RATING: 'KS(JIS)',
  PLUG_DISC_BALL: 'SUS304 (CF8) + (Stellited)',
  FR_UNIT: 'Kg/s',
  IP_UNIT: 'bar(a)',
  OP_UNIT: 'bar(a)',
  IT_UNIT: 'K',
  D_UNIT: 'kg/l',
  Molecular: 'kg/k',
  CUST_NAME: sessionStorage.getItem('CUST_NAME'),
  EST_REQ_EMP: sessionStorage.getItem('REC_NAME'),
  M_ID: sessionStorage.getItem('U_ID'),
  PROJECT: sessionStorage.getItem('PROJECT'),
  FR_MAX: 1,
  FR_NOR: 1,
  FR_MIN: 1,
  IP_MAX: 1,
  IP_NOR: 1,
  IP_MIN: 1,
  OP_MAX: 1,
  OP_NOR: 1,
  OP_MIN: 1,
  IT_MAX: 1,
  IT_NOR: 1,
  IT_MIN: 1,
  D_NOR: 'Density',
  MW_NOR: 'Molecular',
  MW_UNIT: 'kg/kmol',
}
